;; Code generated by the Delta compiler
(module
  (func
    (export "_start")
    (result i32)
    i32.const 6
    i32.const 2
    i32.div_s
    i32.const 1
    i32.const 2
    i32.add
    i32.mul
  )
)
